cryptomator/cryptofs

src/main/java/org/cryptomator/cryptofs/health/api/CommonDetailKeys.java
src/main/java/org/cryptomator/cryptofs/health/api/DiagnosticResult.java
src/main/java/org/cryptomator/cryptofs/health/dirid/DirIdCollision.java
src/main/java/org/cryptomator/cryptofs/health/dirid/HealthyDir.java
src/main/java/org/cryptomator/cryptofs/health/dirid/MissingDirectory.java
src/main/java/org/cryptomator/cryptofs/health/dirid/ObeseDirFile.java
src/main/java/org/cryptomator/cryptofs/health/dirid/OrphanDir.java

The `DiagnosticResult` interface has a new method:
```Java
/**
* Get more specific info about the result like names of affected resources.
*
* @return A map of strings containing result specific information
*/
default Map<String, String> details() {
return Map.of();
}
```
For all already existing ResultImpl the method is overridden providing specific info.

Extend HealthAPI to get more specific information about results

---

pom.xml
src/main/java/org/cryptomator/cryptofs/common/Constants.java
src/main/java/org/cryptomator/cryptofs/health/api/DiagnosticResult.java
src/main/java/org/cryptomator/cryptofs/health/dirid/OrphanDir.java
src/test/java/org/cryptomator/cryptofs/health/dirid/OrphanDirTest.java

This PR implements the `OrphanDir::fix` method.
The fix is implemented in a way that it restricts itself only to fixing the orphan dir problem. Other problems like a missing or too big `dir.c9r` are ignored. Hence, the fix must preserve the shortend property of a ciphertext file.
To get an understanding, consider an orphaned ciphertext dir with a shortened file, where `content.c9r` is missing:
```
-d/NC/RWII6WWFYQTWWEMBXK4OOLUMUHT6PX
|- 7HkyoIUdCinG8NxXbwD5hD6nNsE=.c9s
|- name.c9s
// missing content.c9s
```
Since the content.c9s is missing, the file cannot be simply unshortend. By keeping the file shortened, it is ensured that the orphaned directory can be integrated into the vault structure without stopping at these errors.
All files inside the orphaned directory will be moved to a …

Health-API: Implement OrphanDir.fix()

---

src/main/java/org/cryptomator/cryptofs/health/dirid/DirIdCheck.java
src/main/java/org/cryptomator/cryptofs/health/dirid/EmptyDirFile.java
src/test/java/org/cryptomator/cryptofs/health/dirid/DirIdCheckTest.java

This PR adds to the Directory Check the `EmptyDirFileResult`.
It indicates, that a dir.c9r file exists, but it is empty.
The suggested, but yet not implemented fix is to remove this dir file and its parent, such that the name is not blocked in this directory without any apparent reason for the user.

Health API / Directory Check: Result EmptyDirFile

---

src/main/java/org/cryptomator/cryptofs/LongFileNameProvider.java
src/main/java/org/cryptomator/cryptofs/health/shortened/NotDecodableLongName.java
src/main/java/org/cryptomator/cryptofs/health/shortened/ShortenedNamesCheck.java
src/main/java/org/cryptomator/cryptofs/health/shortened/TrailingBytesInNameFile.java
src/main/java/org/cryptomator/cryptofs/health/shortened/TrailingNullBytesInNameFile.java
src/test/java/org/cryptomator/cryptofs/LongFileNameProviderTest.java
src/test/java/org/cryptomator/cryptofs/health/shortened/ShortenedNamesCheckTest.java
src/test/java/org/cryptomator/cryptofs/health/shortened/TrailingNullBytesInNameFileTest.java

This closes #121.
It adds two additional results to the shortend health check:
* `NotDecodableLongName` if the long filename ist not base64url encoded
* `TrailingNullBytes` if the stored string in name.c9s is affected by issue #121

Feature: Do not add nullbytes when persisting Long Filename

---

src/main/java/org/cryptomator/cryptofs/DirectoryIdBackup.java
src/main/java/org/cryptomator/cryptofs/health/dirid/OrphanDir.java
src/test/java/org/cryptomator/cryptofs/DirectoryIdBackupTest.java
src/test/java/org/cryptomator/cryptofs/health/dirid/OrphanDirTest.java

Closes #126.
This PR allows to restore also filenames of an orphaned directory, if the dirId file is present.
It is implemented in a failsafe way: If the dirId file does not exists, cannot be read or does not match, the orphan cipher dir is recovered without it.

Use dirid file in orphan dir fix

---

src/main/java/org/cryptomator/cryptofs/CryptoFileSystemImpl.java
src/test/java/org/cryptomator/cryptofs/CryptoFileSystemImplTest.java

Closes #132.
Destructive methods (`createDirectory`, `delete`, `copy` and `move`) are adjusted to throw an Filesystemexception when the root path is a parameter.

Handle root path as filesystem API parameter gracefully

---

src/main/java/org/cryptomator/cryptofs/health/dirid/DirIdCheck.java
src/main/java/org/cryptomator/cryptofs/health/dirid/MissingDirIdBackup.java
src/main/java/org/cryptomator/cryptofs/health/dirid/MissingDirIdFile.java

Closes #128.
The result has severity `WARN`. 
The fix is to create the backup file.
The result is created, when a healthy Dir without the backup file is found.

Add "missing dirid backup file" result to directory check

---

src/main/java/org/cryptomator/cryptofs/attr/CryptoBasicFileAttributes.java

the old implementation returns wrong file size for symbolic links, e.g. file `symlink` after `ln -s . symlink` should be 1

fix `CryptoBasicFileAttributes` #GH-141

---

src/main/java/org/cryptomator/cryptofs/health/api/DiagnosticResult.java
src/main/java/org/cryptomator/cryptofs/health/dirid/LooseDirFile.java
src/main/java/org/cryptomator/cryptofs/health/dirid/MissingContentDir.java
src/main/java/org/cryptomator/cryptofs/health/dirid/MissingDirIdBackup.java
src/main/java/org/cryptomator/cryptofs/health/dirid/OrphanContentDir.java
src/main/java/org/cryptomator/cryptofs/health/shortened/LongShortNamesMismatch.java
src/main/java/org/cryptomator/cryptofs/health/shortened/TrailingBytesInNameFile.java
src/test/java/org/cryptomator/cryptofs/health/dirid/LooseDirFileTest.java
src/test/java/org/cryptomator/cryptofs/health/dirid/MissingContentDirTest.java
src/test/java/org/cryptomator/cryptofs/health/dirid/MissingDirIdBackupTest.java
src/test/java/org/cryptomator/cryptofs/health/dirid/OrphanDirTest.java
src/test/java/org/cryptomator/cryptofs/health/shortened/LongShortNamesMismatchTest.java
src/test/java/org/cryptomator/cryptofs/health/shortened/TrailingNullBytesInNameFileTest.java

Currently, the (undocumented) convention for an implementaiton of `DiagnosticResult` is the following:
result severity  != `WARN` → do not override `fix()` method. (aka throws `UnsupportedOperationException`).
In the context of https://github.com/cryptomator/cryptofs/issues/128, this convention showed a lack of flexibility. The dirId backup file is an optional feature, but the result stating it's missing has a severity of `WARN` to be fixable.
Additionally, a lib consumer is unable to reach an intact vault structure once a critical error appears. This leads to reserved file paths, undeletable resources and other permament errors.
This PR solves those problems by discarding the aforementioned convention. The ideas are
* give the consumer the information she needs to make decisions
* …

Health API: Decouple result fix from severity

---

src/main/java/org/cryptomator/cryptofs/CryptoFileSystemComponent.java
src/main/java/org/cryptomator/cryptofs/CryptoFileSystems.java
src/main/java/org/cryptomator/cryptofs/attr/AttributeComponent.java
src/main/java/org/cryptomator/cryptofs/attr/AttributeProvider.java
src/main/java/org/cryptomator/cryptofs/attr/AttributeViewComponent.java
src/main/java/org/cryptomator/cryptofs/attr/AttributeViewProvider.java
src/main/java/org/cryptomator/cryptofs/ch/ChannelComponent.java
src/main/java/org/cryptomator/cryptofs/dir/DirectoryStreamComponent.java
src/main/java/org/cryptomator/cryptofs/dir/DirectoryStreamFactory.java
src/main/java/org/cryptomator/cryptofs/fh/OpenCryptoFile.java
src/main/java/org/cryptomator/cryptofs/fh/OpenCryptoFileComponent.java
src/main/java/org/cryptomator/cryptofs/fh/OpenCryptoFiles.java
src/test/java/org/cryptomator/cryptofs/CryptoFileSystemsTest.java
src/test/java/org/cryptomator/cryptofs/attr/AttributeProviderTest.java
src/test/java/org/cryptomator/cryptofs/dir/DirectoryStreamFactoryTest.java
src/test/java/org/cryptomator/cryptofs/fh/OpenCryptoFileTest.java
src/test/java/org/cryptomator/cryptofs/fh/OpenCryptoFilesTest.java

This PR replaces all dagger `@Subcomponent.Builder`s with dagger [Factories](https://dagger.dev/api/latest/dagger/Component.Factory.html).
Factories guarentee to always return a new instance and do not have a public state, hence they are threadsafe.

Feature: Use dagger factories instead of builders

---

src/main/java/org/cryptomator/cryptofs/CryptoFileSystemImpl.java
src/main/java/org/cryptomator/cryptofs/ch/CleartextFileChannel.java
src/main/java/org/cryptomator/cryptofs/fh/OpenCryptoFile.java
src/main/java/org/cryptomator/cryptofs/fh/OpenCryptoFileModule.java
src/main/java/org/cryptomator/cryptofs/fh/OpenCryptoFiles.java
src/test/java/org/cryptomator/cryptofs/CryptoFileChannelWriteReadIntegrationTest.java
src/test/java/org/cryptomator/cryptofs/CryptoFileSystemImplTest.java
src/test/java/org/cryptomator/cryptofs/ch/CleartextFileChannelTest.java

Fixes #170.
Before actually deleting files on the underlying file system, the openCryptoFile is removed from the (path, file)-mapping. Additionally, the `currentFilePath` object is null'ed, to indicate the openCryptoFile should not be used anymore. The usages of `currentFilePath` are updated to be null safe.
Note, that this only fixes a "symptom", there is still surface for bad timing. The root cause is described in #171.

Feature: Remove deleted file from openFiles map and set file path to null

---

src/main/java/org/cryptomator/cryptofs/fh/ChunkCache.java
src/test/java/org/cryptomator/cryptofs/CryptoFileChannelWriteReadIntegrationTest.java

Fixes #173
The chunk data is directly modified. This might lead to data corruption when writing unsynchronized to the same file from different file channels, but the library consumer must handle synchronization.

Use Chunk.data() directly when putting chunk

---

src/main/java/org/cryptomator/cryptofs/CryptoPathMapper.java
src/test/java/org/cryptomator/cryptofs/CryptoPathMapperTest.java

Closes #180.
I applied the workaround described in [Caffeine wiki](https://github.com/ben-manes/caffeine/wiki/Faq#recursive-computations). Additonally, i checked all other spots where we use a `Cache` or `LoadingCache` for recursive updates:
* LongFileNameProvider
* ChunkCache
* DirectoryIdProvider
None of the above do such recursive updates, hence i left them untouched.

Feature: Do not recursively update cache

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/dependency-check.yml
pom.xml

This PRs changes the way, how we use the https://github.com/jeremylong/DependencyCheck maven plugin.
Changes were necessary due to the deprecation of an API used by dependency check (see [here](https://github.com/jeremylong/DependencyCheck#900-upgrade-notice) for details).
Changes:
* Plugin updated to 9.0.4
* plugin uses an NVD API key
* only before a release the plugin is executed
* once a week, the plugin is run on CI. If a vulnerability is detected, the workflow fails and the report is uploaded.

Feature: Refactor OWASP dependency check runs

---

src/main/java/org/cryptomator/cryptofs/attr/CryptoBasicFileAttributeView.java
src/main/java/org/cryptomator/cryptofs/ch/ChannelCloseListener.java
src/main/java/org/cryptomator/cryptofs/ch/CleartextFileChannel.java
src/main/java/org/cryptomator/cryptofs/fh/OpenCryptoFile.java
src/test/java/org/cryptomator/cryptofs/ch/CleartextFileChannelTest.java

This PR changes the logic of persisting the lastModfied date from _before_ closing the ciphertext channel to _afterwards_. Additionally, the cryptofs internal lastModifiedDate is always updated, even when persisting to storage fails.
This impl change is motivated by the behaviour of some fs/storage implemenations, which set the lastModified time to "now" when closing a channel, regardless of changes made.
Before merging, we should test the implementation with different scenarios:
|         | OneDrive | pCloud | GoogleDrive | iCloud | Dropbox | LocalFS |
|---------|----------|--------|-------------|--------|----------|----------|
| Windows |      ✅    |  ✅    |     ✅         |   ❓1      |      ✅    |     ✅    |
| macOS   |     ✅     |   ✅     |     ✅        |   ✅     |  ✅ | ✅  | 
| Linux …

Feature: First close file channel, then persist lastModified

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependency-check.yml
.github/workflows/publish-central.yml
.github/workflows/publish-github.yml
.idea/misc.xml
README.md
pom.xml
src/test/java/org/cryptomator/cryptofs/CryptoFileSystemImplTest.java
src/test/java/org/cryptomator/cryptofs/CryptoPathMapperTest.java

This PR updates the project to JDK 21.
Notable adjustments:
* update of mockito to version 5.12.0 and adjusting tests

Feature: JDK 21

---

src/main/java/org/cryptomator/cryptofs/CryptoFileSystemImpl.java
src/main/java/org/cryptomator/cryptofs/CryptoFileSystemProvider.java
src/main/java/org/cryptomator/cryptofs/DirectoryIdBackup.java
src/main/java/org/cryptomator/cryptofs/common/Constants.java
src/main/java/org/cryptomator/cryptofs/dir/C9rConflictResolver.java
src/main/java/org/cryptomator/cryptofs/dir/DirectoryStreamFilters.java
src/main/java/org/cryptomator/cryptofs/health/dirid/DirIdCheck.java
src/main/java/org/cryptomator/cryptofs/health/dirid/MissingContentDir.java
src/main/java/org/cryptomator/cryptofs/health/dirid/MissingDirIdBackup.java
src/main/java/org/cryptomator/cryptofs/health/dirid/ObeseDirFile.java
src/main/java/org/cryptomator/cryptofs/health/dirid/OrphanContentDir.java
src/test/java/org/cryptomator/cryptofs/CryptoFileSystemImplTest.java
src/test/java/org/cryptomator/cryptofs/CryptoFileSystemProviderTest.java
src/test/java/org/cryptomator/cryptofs/DeleteNonEmptyCiphertextDirectoryIntegrationTest.java
src/test/java/org/cryptomator/cryptofs/DirectoryIdBackupTest.java
src/test/java/org/cryptomator/cryptofs/health/dirid/MissingContentDirTest.java
src/test/java/org/cryptomator/cryptofs/health/dirid/MissingDirIdBackupTest.java
src/test/java/org/cryptomator/cryptofs/health/dirid/OrphanContentDirTest.java

This PR extends the `DirectoryIdBackup` class by a read method. At the same time, some used/touched entities to make their purpose more clear.
By moving the read method to the DirectoryIdBackup class, we have a centralized object to "manage" this feature. Future changes will benefit from this by simply calling one of the two methods of the class without thinking about implementation. This also dedups code in the `OrphanContentDir` fix.

Feature: Extend dir id backup class

---

src/main/java/org/cryptomator/cryptofs/ch/ChannelCloseListener.java
src/main/java/org/cryptomator/cryptofs/ch/ChannelComponent.java
src/main/java/org/cryptomator/cryptofs/ch/CleartextFileChannel.java
src/main/java/org/cryptomator/cryptofs/fh/ChunkIO.java
src/main/java/org/cryptomator/cryptofs/fh/OpenCryptoFile.java
src/test/java/org/cryptomator/cryptofs/ch/CleartextFileChannelTest.java
src/test/java/org/cryptomator/cryptofs/fh/OpenCryptoFileTest.java

As already observed in other PRs, the class `OpenCryptoFile` can be simplified. This PR applies these simplifications.
* replaced ChannelCloseListener interface by `Consumer<FileChannel>`
* changed type of openChannels counter to `AtomicInteger`

Refactoring: Simplify OpenCryptoFile

---

src/main/java/org/cryptomator/cryptofs/CryptoFileSystems.java
src/main/java/org/cryptomator/cryptofs/common/FileSystemCapabilityChecker.java
src/main/java/org/cryptomator/cryptofs/migration/MigrationModule.java
src/main/java/org/cryptomator/cryptofs/migration/Migrators.java
src/main/java/org/cryptomator/cryptofs/migration/v7/Version7Migrator.java
src/test/java/org/cryptomator/cryptofs/CryptoFileSystemsTest.java
src/test/java/org/cryptomator/cryptofs/common/FileSystemCapabilityCheckerTest.java
src/test/java/org/cryptomator/cryptofs/migration/MigratorsTest.java

This PR does two, related things:
1. Removes the implicit read-only flag, if the storage location is read only.
1. Refactors the `FileSystemCapabilityChecker` class to be static only
>Imagine, someone needs a tshirt and decides to order a green one. Unfortunately, she gets a red one, because green is out of stock. Not cool, she wanted a green one. Instead, the customer should have been informed about the the low stock and _asked_ what to do.
One can argue, but the color does not matter, since you can always wear the shirt. But we don't know the purpose of the shirt. If it is used in a green screen setting, red is definitively a bad color.
This PR applies the principle behind the short story when creating the cryptographic filesystem. The implicit change from read/write to read-only, if …

Feature: Refactor filesystem checker

---

src/main/java/org/cryptomator/cryptofs/CryptoFileSystem.java
src/main/java/org/cryptomator/cryptofs/CryptoFileSystemImpl.java
src/main/java/org/cryptomator/cryptofs/FileNameDecryptor.java
src/test/java/org/cryptomator/cryptofs/CryptoFileSystemImplTest.java
src/test/java/org/cryptomator/cryptofs/DirectoryIdBackupTest.java
src/test/java/org/cryptomator/cryptofs/FileNameDecryptorTest.java
src/test/java/org/cryptomator/cryptofs/health/dirid/OrphanContentDirTest.java
src/test/java/org/cryptomator/cryptofs/util/TestCryptoException.java

This PR adds the method `getCleartextName(Path p)` to the CryptoFileSystem interface, which decrypts the filename of the given path and return the cleartext name.
Note: The method does not compute the whole cleartext path, since for this a recursive directory listing of the cryptoFileSystem is needed.
The feature is encapsulated in its own class `FileNameDecryptor`, which first validates the input path and second tries to decrypt it by using the [DirId backup file](https://github.com/cryptomator/cryptofs/pull/118). If the directory does not have such a file, an `UnsupportedOperationException` is thrown.

Feature: Public method for decrypting ciphertext name.

---

src/main/java/org/cryptomator/cryptofs/fh/OpenCryptoFile.java
src/test/java/org/cryptomator/cryptofs/CryptoFileChannelWriteReadIntegrationTest.java
src/test/java/org/cryptomator/cryptofs/fh/OpenCryptoFileTest.java

This PR fixes #269.
Instead of writing an "optimized", but wrong truncate block, we can simply use `CleartextChannel.truncate(0)` when opening a new file. Benefit of this method: It is already tested! And since it is synchronized and also creating a new file channel is synchronized, we can be sure that side calls cannot interfere.

Use truncate() of CleartextChannel when opening new Channel with `TRUNCATE_EXISTING`

---

pom.xml
src/main/java/org/cryptomator/cryptofs/dir/C9rConflictResolver.java
src/main/java/org/cryptomator/cryptofs/dir/C9rDecryptor.java
src/test/java/org/cryptomator/cryptofs/dir/Base64UrlRegexTest.java
src/test/java/org/cryptomator/cryptofs/dir/C9rConflictResolverTest.java
src/test/java/org/cryptomator/cryptofs/dir/C9rDecryptorTest.java

This change attempts to solve cryptomator/cryptomator#3707.
The first commit is just a slight improvement for the regex matcher in order to make it faster and more robust.
The second commit alters the `renameConflictingFile()` method, which is now rather big, but I feel like it is the right amount of readability for this project. This is the new logic:
1. assume that a sync client adds a "conflict suffix" to the end of the file (but before the file extension)
2. extract this conflict suffix by looking at the part _after the ciphertext_ and _before the `.c9r` extension_
3. apply some length limiting to the extracted suffix and the cleartext name to not exceed the max filename length (to not trigger filename shortening)
4. assemble new cleartext name `lengthLimitedBasname + …

Use Conflict Suffixes from Ciphertext Files

---

src/main/java/org/cryptomator/cryptofs/CryptoPathMapper.java
src/main/java/org/cryptomator/cryptofs/DirectoryIdLoader.java
src/main/java/org/cryptomator/cryptofs/event/BrokenDirFileEvent.java
src/main/java/org/cryptomator/cryptofs/event/BrokenFileNodeEvent.java
src/main/java/org/cryptomator/cryptofs/event/DecryptionFailedEvent.java
src/main/java/org/cryptomator/cryptofs/event/FilesystemEvent.java
src/main/java/org/cryptomator/cryptofs/fh/FileHeaderHolder.java
src/test/java/org/cryptomator/cryptofs/CryptoPathMapperTest.java
src/test/java/org/cryptomator/cryptofs/DirectoryIdLoaderTest.java
src/test/java/org/cryptomator/cryptofs/fh/FileHeaderHolderTest.java

This PR adds mainly to new [events](https://github.com/cryptomator/cryptofs/pull/277):
* BrokenDirFileEvent: If the directory link file (dir.c9r) is empty or obese, thus breaking cleartext paths
* BrokenFileNodeEvent: If a c9r directory does not contain any identification file

Feature: More events and event refinement 

---

src/main/java/org/cryptomator/cryptofs/event/BrokenDirFileEvent.java
src/main/java/org/cryptomator/cryptofs/event/BrokenFileNodeEvent.java
src/main/java/org/cryptomator/cryptofs/event/ConflictResolutionFailedEvent.java
src/main/java/org/cryptomator/cryptofs/event/ConflictResolvedEvent.java
src/main/java/org/cryptomator/cryptofs/event/DecryptionFailedEvent.java
src/main/java/org/cryptomator/cryptofs/event/FilesystemEvent.java

Relates to #277 
This PR extends the `FilesystemEvent` interface by a `getTimestamp` method and adds a timestamp field to every subclass of `FilesystemEvent`

Feature: Add timestamp to file system events

---

src/main/java/org/cryptomator/cryptofs/CiphertextPathValidations.java
src/main/java/org/cryptomator/cryptofs/DirectoryIdBackup.java
src/main/java/org/cryptomator/cryptofs/FileNameDecryptor.java
src/test/java/org/cryptomator/cryptofs/DirectoryIdBackupTest.java
src/test/java/org/cryptomator/cryptofs/FileNameDecryptorTest.java
src/test/java/org/cryptomator/cryptofs/health/dirid/OrphanContentDirTest.java

This PR fixes #289.
Additionally, it adds a path validation in the `DirectoryIdBackup#read` method. Since the path validation might be reused in the future, it is moved to its own class.

Fix DecryptFileName feature
